## Travis CI Integration

language: csharp
mono: 4.0.0
sudo: false
addons:
  apt:
    packages:
    - nunit-console
    - mono-devel
    - mono-gmcs
script:
  - xbuild LuaParser.sln
  - nunit-console bin/Debug/LuaParserTests.dll
