## Travis CI Integration

language: csharp
solution: DW.Lua.sln
mono: latest
sudo: false

env:
 global:
  - EnableNuGetPackageRestore=true 

addons:
  apt:
    packages:
    - nunit-console
script:
  - nuget restore DW.Lua.sln
  - xbuild /p:Configuration=Release DW.Lua.sln
  - nunit-console bin/Release/DW.Lua.UnitTests.dll
