## Travis CI Integration

language: csharp
mono: 4.0.0
sudo: false

env:
 global:
  - EnableNuGetPackageRestore=true 

addons:
  apt:
    packages:
    - nunit-console
script:
  - xbuild DW.Lua.sln
  - nunit-console bin/Debug/DW.Lua.Tests.dll
